services:
  database:
    image: postgres:18.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: benjrm
      POSTGRES_USER: benjrm
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U benjrm -d benjrm"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./database:/var/lib/postgresql
    ports:
      - 5432:5432
