services:
  identity-provider:
    image: quay.io/keycloak/keycloak:26.6.1
    ports:
      - "8088:8088"
      - "9000:9000"
    volumes:
      - ./setup-identity-provider.sh:/setup-identity-provider.sh
    env_file:
      - .env.example
    entrypoint: ["/bin/bash", "/setup-identity-provider.sh"]

    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\nHost: http://127.0.0.1:8000\nConnection: close\n\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;" ]
      start_period: "15s"
      interval: 30s
      timeout: 10s
      retries: 3