import { defaultSchema } from "rehype-sanitize"

const sanitizeSchema = {
    ...defaultSchema,
    clobberPrefix: "", // Prevents rehype-sanitize from prefixing attributes like "id" with "user-content-" required to support footnote functionality
    tagNames: [
        ...(defaultSchema.tagNames ?? []),
        "main",
        "section",
        "nav",
        "article",
        "aside",
        "header",
        "footer",
        "address",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "p",
        "hr",
        "ol",
        "ul",
        "li",
        "dl",
        "dt",
        "dd",
        "blockquote",
        "pre",
        "code",
        "table",
        "thead",
        "tbody",
        "tfoot",
        "tr",
        "th",
        "td",
        "caption",
        "colgroup",
        "col",
        "a",
        "em",
        "strong",
        "small",
        "s",
        "cite",
        "q",
        "dfn",
        "abbr",
        "data",
        "time",
        "var",
        "samp",
        "kbd",
        "sub",
        "sup",
        "i",
        "b",
        "u",
        "mark",
        "ruby",
        "rt",
        "rp",
        "bdi",
        "bdo",
        "span",
        "br",
        "wbr",
        "ins",
        "del",
        "picture",
        "img",
        "figure",
        "figcaption",
        "video",
        "audio",
        "source",
        "track",
        "map",
        "area",
        "fieldset",
        "legend",
        "label",
        "input",
        "select",
        "optgroup",
        "option",
        "details",
        "summary",
        "progress",
        "meter",
        "template",
    ],
    attributes: {
        ...defaultSchema.attributes,
        a: [
            ...(defaultSchema.attributes?.a ?? []),
            "target",
            "rel",
            "download",
            "href",
            "id",
            "data-footnote-backref",
        ],
        li: [...(defaultSchema.attributes?.li ?? []), "id"],
        img: [...(defaultSchema.attributes?.img ?? []), "width", "height", "loading", "decoding"],
        video: [
            ...(defaultSchema.attributes?.video ?? []),
            "width",
            "height",
            "controls",
            "autoplay",
            "muted",
            "loop",
            "playsinline",
        ],
        audio: [
            ...(defaultSchema.attributes?.audio ?? []),
            "controls",
            "autoplay",
            "muted",
            "loop",
        ],
        source: [...(defaultSchema.attributes?.source ?? []), "src", "type", "media"],
        input: [
            ...(defaultSchema.attributes?.input ?? []),
            ["type", "checkbox"],
            "checked",
            "disabled",
        ],
        code: [
            ...(defaultSchema.attributes?.code ?? []),
            ["class", /^language-/],
            ["className", /^language-/],
        ],
        pre: [...(defaultSchema.attributes?.pre ?? []), ["class", true], ["className", true]],
        span: [...(defaultSchema.attributes?.span ?? []), ["class", true], ["className", true]],
        sup: [...(defaultSchema.attributes?.sup ?? []), ["class", true], ["className", true], "id"],
        "*": [
            ...(defaultSchema.attributes?.["*"] ?? []),
            "id",
            "class",
            "className",
            "title",
            "alt",
            "role",
            "name",
            /^data-/,
            /^data/,
            /^aria-/,
        ],
    },
}

export default sanitizeSchema
