#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${KC_DB_USERNAME} WITH PASSWORD '${KC_DB_PASSWORD}';
	CREATE DATABASE ${KEYCLOAK_DATABASE};
	GRANT ALL PRIVILEGES ON DATABASE ${KEYCLOAK_DATABASE} TO ${KC_DB_USERNAME};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${KEYCLOAK_DATABASE}" <<-EOSQL
  	GRANT ALL ON SCHEMA public TO ${KC_DB_USERNAME};
  	GRANT SELECT ON pg_class TO ${KC_DB_USERNAME};
  	GRANT SELECT ON pg_namespace TO ${KC_DB_USERNAME};
EOSQL
