# https://schemathesis.readthedocs.io/en/stable/reference/configuration/#base-url
base-url = "http://localhost:8080"

# https://schemathesis.readthedocs.io/en/stable/reference/configuration/#hooks
hooks = "src.hooks"

# https://schemathesis.readthedocs.io/en/stable/reference/configuration/#suppress-health-check
#suppress-health-check = ["filter_too_much"]

# https://schemathesis.readthedocs.io/en/stable/reference/configuration/#seed
seed = 42

[generation]
# https://schemathesis.readthedocs.io/en/stable/reference/configuration/#generationallow-extra-parameters
allow-extra-parameters = false
# https://schemathesis.readthedocs.io/en/stable/reference/configuration/#generationallow-x00
allow-x00 = false
# https://schemathesis.readthedocs.io/en/stable/reference/configuration/#generationdeterministic
deterministic = true
# https://schemathesis.readthedocs.io/en/stable/reference/configuration/#generationdatabase
# note: deterministic = true requires database = "none" to avoid non-deterministic test generation due to the use of a database
database = "none"


[phases.examples]
enabled = true

[phases.coverage]
enabled = true

[phases.fuzzing]
enabled = true

[phases.stateful]
enabled = true

[reports.junit]
enabled = true

[reports.har]
enabled = true
