name: Linting pipeline
run-name: Linting for ${{ github.event_name }} by @${{ github.actor }}

on:
  push:
    branches:
      - main
      - 'feature/*'
    paths:
      - "frontend/**"
      - "backend/**"
      - ".github/workflows/lint.yml"
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"
      - ".github/workflows/lint.yml"
  workflow_dispatch:

# Cancel concurrent running workflows, after a new one is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  #
  # Check which linting job to run (Frontend or Backend)
  #
  check_changes:
    name: "Detect changed Files"
    runs-on: ubuntu-latest
    # Skip pull_request event for internal PRs (push covers it)
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
      docker: ${{ steps.filter.outputs.docker }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
            docker:
              - 'docker/**'
              - 'Dockerfile*'
              - 'docker-compose*'

  # Frontend Linting
  frontend_lint:
    name: "Frontend Linting with ESLint"
    runs-on: ubuntu-latest
    needs: check_changes
    if: needs.check_changes.outputs.frontend == 'true' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"
      - name: Install dependencies
        run: cd "frontend" && npm ci --prefer-offline
      - name: Type-Check
        run: cd "frontend" && npm run type:check
      - name: Lint & Format Check
        run: cd "frontend" && npm run lint

  # Backend Linting & Formatting
  backend_lint:
    name: "Rust Linting for Backend"
    runs-on: ubuntu-latest
    needs: check_changes
    if: needs.check_changes.outputs.backend == 'true' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Clippy (debug)
        run: cargo clippy --all-features -- --deny warnings
        working-directory: backend
      - name: Create empty dist folder for release linting check
        run: mkdir -p frontend/dist
      - name: Clippy (release)
        run: cargo clippy --all-features --release -- --deny warnings
        working-directory: backend
      - name: Check formatting
        run: cargo fmt --check
        working-directory: backend
