name: API Testing with Schemathesis
on:
  push:
    branches:
      - 'main'
    paths:
      - 'docs/openapispec/**'
      - 'backend/**'
      - '.github/workflows/schemathesis.yaml'
  pull_request:
    paths:
      - 'docs/openapispec/**'
      - 'backend/**'
      - '.github/workflows/schemathesis.yaml'
  workflow_dispatch:

jobs:
  test:
    permissions:
      # Because the action needs to comment on the PR with the coverage summary powered
      # by [TraceCov](https://docs.tracecov.sh/) we need to give it write permissions to pull requests.
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Start API
        run: |
          PORT=8080 cargo run --manifest-path backend/Cargo.toml &
          curl --retry 5 --retry-delay 2 --retry-connrefused http://localhost:8080/api/health
          echo "API is healthy."
        env:
          DATABASE_URL: 'sqlite::memory:'
          PORT: '8080'
      - uses: schemathesis/action@v3
        with:
          schema: 'docs/openapispec/RestInterface.yaml'
          base-url: 'http://localhost:8080'
          version: '4.18.5'
