name: Run Spectral on Pull Requests
on:
  pull_request:
    paths:
      - 'docs/openapispec/RestInterface.yaml'
      - '.github/workflows/spectral.yaml'
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Spectral - An open-source API style guide enforcer and linter.
        run: npm install -g @stoplight/spectral-cli
      - name: Run spectral lint
        run: spectral lint docs/openapispec/RestInterface.yaml -f sarif -o spectral-lint-results.sarif
      - name: Upload Spectral lint results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'spectral-lint-results.sarif'